import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import getCurrentUser from "./actions/getCurrentUser";
import ToastProvider from "@/components/ToastProvider";
import NavBar from "@/components/NavBar";
import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar currentUser={currentUser}/>
        <ToastProvider/>
        {children}
        <link href="https://fonts.googleapis.com/css2?family=Abel&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet"/>
        <script src="js/matter.min.js"></script>
      </body>
    </html>
  );
}
